# -*- coding: utf-8 -*-

import os
from PyQt5 import QtWidgets
import pandas as pd

loaded_data = None
loaded_spectra = None

##!!! TO DO: combine with other load_data.py modules and make a general Loader Class for /toolbox

def load_spectra(file_name, file_ext, file_desc):
    if file_ext == ".csv":
        separator = ','
    elif file_ext == ".dat":
        separator = '\t'
    
    df = pd.read_csv(file_name, sep=separator)
    return df

def load_full(loaded_data):
    ##!!! take into account non-Spectragryph format
    wavelengths = loaded_data.iloc[:, 0].values
    wavenumbers = loaded_data.iloc[:, 1].values ## obtained from .dat file generated by Spectragryph
        ##!!! if not available: convert wavelength to wavenumbers
    loaded_spectra = loaded_data.iloc[:, 2:].values ## for SpectraGryph format
    
    first_spectrum = loaded_spectra[:, 0]
    last_spectrum = loaded_spectra[:, -1]
    number_of_spectra = loaded_spectra.shape[1]
    
    return wavelengths, wavenumbers, loaded_spectra, first_spectrum, last_spectrum, number_of_spectra


