# -*- coding: utf-8 -*-
import pandas as pd

loaded_data = None
loaded_spectra = None

##!!! CONVERT TO CLASS CALLED Loader

def load_spectra(file_name, file_ext, file_desc):
    if file_ext == ".csv":
        separator = ','
    elif file_ext in (".txt",".dat"):
        separator = '\t'
    
    df = pd.read_csv(file_name, sep=separator)
    return df

def load_spectrum(loaded_data, wavenumbers_only=False):
    ##!!! add option to load with first column being wavenumber
    
    if wavenumbers_only:
        wavelengths = None
        wavenumbers = loaded_data.iloc[:, 0].values ## obtained from .dat file generated by Spectragryph
        spectrum = loaded_data.iloc[:, 1].values ## for SpectraGryph format
    else:
        if len(loaded_data.columns) == 2:
            wavelengths = loaded_data.iloc[:, 0].values
            wavenumbers = wavenumbers_from_wavelengths(wavelengths) ## convert wavelength to wavenumbers
            spectrum = loaded_data.iloc[:, 1].values  
        elif len(loaded_data.columns) == 3:
            wavelengths = loaded_data.iloc[:, 0].values
            wavenumbers = loaded_data.iloc[:, 1].values ## obtained from file
            spectrum = loaded_data.iloc[:, 2].values 
        else:
            print("something wrong with loaded data (number of columns is not 2 or 3)")
    
    return wavelengths, wavenumbers, spectrum

def wavenumbers_from_wavelengths(wavelengths):
    wavenumbers = 1e7/wavelengths
    return wavenumbers